import random
import src.utils as utils
from src.logs_generators.log import *

class SSHAuthenticationLogs(Log):
    """
    This class is used to generate logs simulating the ones generated by a SSH
    services. Only SSH authentication logs are forged in this class, reporting
    a successful, invalid of failing connection attempt.

    Here, the format used is the following:
        mmm dd hh:mm:ss SERVER_NAME sshd[PID]: DESCRIPTION

    See: https://en.wikibooks.org/wiki/OpenSSH/Logging_and_Troubleshooting

    Attributes
    ----------
    _LOG_PROCESS : str
        The constant SSH process generating the log. Because we only focus on
        authentication here, it is made of a single process name. But others
        can be found from the SSH namely sudo, useradd, groupadd.

    Methods
    -------
    str()
        Generates a random log simulation the report of an authentication to a 
        host using SSH.
    """

    _LOG_PROCESS = "sshd"
    
    def __init__(self) -> None:
        super().__init__()

    def _generate_log(self):
        """Generates a random log, without timestamp, simulating one reporting a
        connection attempt to a device using SSH under the format:
            SERVER_NAME sshd[PID]: DESCRIPTION

        Parameters
        ----------
        /

        Returns
        -------
        string
            The part of a log such as the one created by a SSH service reporting 
            an authentication attempt without its timestamp (i.e. of format 
            SERVER_NAME sshd[PID]: DESCRIPTION).
        """

        host = utils.generate_random_hostname()
        username = utils.generate_random_username()
        ip_address = utils.generate_random_ipv4_address()
        port_number = str(utils.generate_random_port_number())
        pid = random.randint(1, 32768)
        status = random.choice(["Failed", "Accepted", "Invalid"])

        if(status == "Invalid"):
            return host + " " + self._LOG_PROCESS + "[" + str(pid) + "]: " + \
                   status + " user " + username + " from " + ip_address
        elif(status == "Failed"):
            return host + " " + self._LOG_PROCESS + "[" + str(pid) + "]: " + \
                   status + " password for " + \
                   random.choice(["invalid user ", ""]) + status + username + \
                   " from " + ip_address + " port " + port_number + " ssh2"
        
        return host + " " + self._LOG_PROCESS + "[" + str(pid) + "]: " + \
               status + " password for " + username + " from " + ip_address + \
               " port " + port_number + " ssh2"

    def str(self):
        """Generates a random log simulating an authentication to a host using
        SSH under the format:
            mmm dd hh:mm:ss SERVER_NAME sshd[PID]: DESCRIPTION
        
        See: 
            - https://www.elastic.co/blog/grokking-the-linux-authorization-logs
            - https://en.wikibooks.org/wiki/OpenSSH/Logging_and_Troubleshooting

        Parameters
        ----------
        /

        Returns
        -------
        str
            A random SSH authentication attempt log.
        
        """

        self.update_timestamp()
        return self._timestamp.strftime("%b %d %H:%M:%S") + " " + \
               self._generate_log()
