
LOG_FILE_NAME = "output/infrastructure_logs.log"
USERNAME_FILE = "./data/username.txt"

LOG_DEBUG_LEVEL = 0
LOG_INFO_LEVEL = 1
LOG_WARNING_LEVEL = 2
LOG_ERROR_LEVEL = 3
LOG_FATAL_LEVEL = 4
LOG_LEVELS_STRING = {
    LOG_DEBUG_LEVEL: "DEBUG",
    LOG_INFO_LEVEL: "INFO",
    LOG_WARNING_LEVEL: "WARNING",
    LOG_ERROR_LEVEL: "ERROR",
    LOG_FATAL_LEVEL: "FATAL"
}

NUMBER_OF_THREAD = 5
THREAD_SLEEP_TIME_MIN = 0
THREAD_SLEEP_TIME_MAX = 50

PROBABILITY_LOGGING_CISCO_IOS = 0.1
PROBABILITY_LOGGING_SSH_AUTH = 0.3
PROBABILITY_LOGGING_APPLICATION = 0.9